# Site settings
title: LittleMario
email: root@apoorv.pro
description: > #
  Mario is on a new quest this time to rescue the world,
  him to eliminate the bad guys and catch all Stars.
baseurl: "/LittleMario"
url: "http://apoorvsaxena.github.io"
github_username:  ApoorvSaxena

# Build settings
markdown: kramdown